name: Builder

on:
  push:
    branches:
      - master

jobs:
  images:
    runs-on: ubuntu-latest
    if: github.repository == 'keloran/qmk_firmware'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: textbook/git-checkout-submodule-action@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: qmk setup
        run: util/qmk_install.sh
      - name: File Link
        run: ln -s users/keloran/builder.json .
      - name: Builder
        run: go build users/keloran/builder.go
      - name: Keyboards
        run: ./builder -all
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Keyboards
          path: |
            *.hex
            *.bin
