name: CoffeeBreak

on:
  push:
    branches:
      - master

jobs:
  images:
    runs-on: ubuntu-latest
    if: github.repository == 'keloran/qmk_firmware'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: textbook/git-checkout-submodule-action@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: qmk setup
        run: util/qmk_install.sh
      - name: Kawa
        run: make cbkbd/kawa:default
      - name: Xlant
        run: make cbkbd/xlant:default
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CoffeeBreak
          path: |
            *.hex
            *.bin
