name: Keloran

on:
  push:
    branches:
      - master

jobs:
  images:
    runs-on: ubuntu-latest
    if: github.repository == 'keloran/qmk_firmware'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: textbook/git-checkout-submodule-action@master
      - uses: actions/setup-go@v2
        with:
          go-verison: '1.16.x'
      - name: File Link
        run: |
          ln -s users/keloran/builder.txt .
          go build users/keloran/builder.go
          ./builder sofle